### PR TITLE
fix: fix header width on profile page

### LINKED ISSUE #517: 🐛 Bug | Fix header's width on profile page
We need the header to be the same width everywhere.

On the profile page, the header is in a container of 960px where it should be 1280px.

See an example of bugged header : https://app.sigle.io/jackbinswitch.btc
Should be like this : https://app.sigle.io/jackbinswitch.btc/3IlTtz4ymc7PICXjCCQw0

### PR DESCRIPTION
**Pull request by gregogun**
This pr does the following:
- Fixes incorrect header width on profile page
- Refactors deprecated `Text` components to use new `Typography` components
- Replaces all styled components on the page with stitches

Closes #517

### CODE REVIEW

File: sigle/src/modules/publicHome/components/PublicHome.tsx [hunk 1]
```diff
@@ -116,56 +106,61 @@ export const PublicHome = ({ file, settings }: PublicHomeProps) => {
...
         }}
       />
-
-      <Container>
-        <AppHeader />
-        <Header>
-          {settings.siteLogo && (
-            <HeaderLogo src={settings.siteLogo} alt={`${siteName} logo`} />
+      <AppHeader />
+      <Header>
```
Comment (pradel) [inline sigle/src/modules/publicHome/components/PublicHome.tsx:110]: I think the header should be inside a container, big images won't overflow that way and on mobile you have some padding around :)

**Review by pradel — CHANGES_REQUESTED** [review]

File: sigle/src/modules/publicHome/components/PublicHome.tsx (hunk 1 above)
Comment (gregogun) [reply sigle/src/modules/publicHome/components/PublicHome.tsx:110]: ah yes that makes sense - will update :)
